export {
  PUBLIC_CATEGORIES,
  ADMIN_ONLY_CATEGORIES,
  SYSTEM_CATEGORIES,
  CATEGORY_ICONS,
  collectCategoriesFromItems,
  mergeCategoryLists,
  resolveSystemCategories,
  toCategoryPickerEntries,
  isHighValueCategory,
  isAdminOnlyCategory,
  isJunkCategoryName,
  validateCategoryName,
  canonicalizeCategory,
  categoriesMatch,
} from '../utils/categories';
